pipeline_name: example_pipeline
workspace_path: ./workspace
config_path: ./config
model_hub_name: example_model_hub
datasets:
  - dataset_name: custom
    dataset_class: ListwiseDataset
    dataset_path: ./examples/llumux_example_dataset
    propietary: perf_scorer
    test_size: 0
    random_sample: False
    fixed_len_eval: 100
    fixed_len_train: 100
    list_size: 2
    splits:
      - train
      - validation
  - dataset_name: custom
    dataset_class: PairwiseDataset
    dataset_path: ./examples/llumux_example_dataset
    propietary: cost_scorer
    test_size: 0
    random_sample: False
    fixed_len_eval: 100
    fixed_len_train: 100
    target_scale: 1000
    score_name: word_count_complexity
    splits:
      - train
      - validation
  - dataset_name: custom
    dataset_path: ./examples/llumux_example_dataset
    dataset_class: RouterDataset
    propietary: router
    test_size: 0.000
    random_sample: False
    fixed_len_eval: 100
    fixed_len_train: 100
    splits:
      - test
callbacks:
  - callback_name: checkpoint_callback
    callback_class: CheckpointSaver
    freq: 5
  - callback_name: loss_tracker_callback
    callback_class: LossTracker
    freq: 5
scorers:
  - scorer_name: perf_scorer
    scorer_class: GeneralScorer
    load_from_disk: False
    hidden_size: 8
    prompt_embedder_name: albert-base-v2
    loss_fun_name: pairwise_cross_entropy
    use_frozen_embedder: True
  - scorer_name: cost_scorer
    scorer_class: PairwiseScorer
    load_from_disk: False
    hidden_size: 8
    prompt_embedder_name: albert-base-v2
    loss_fun_name: pairwise_logistic_loss
    use_frozen_embedder: True
trainer:
  batch_size: 2
  lr: 0.0001
  epochs: 2
  eval_freq : 5
router:
  router_class: RatioRouter
  model_hub_name: example_model_hub
  threshold: 1.0
router_evaluator:
  batch_size: 4
